#!/bin/bash
#Script to perform diff test on screenshots
#Runs in folder where screenshots are
#Assumes screenshots were saved as .png files

declare -i counter=0
pic1=""
pic2=""

for pic in *.png
do
  if [ $counter -eq 0 ];
  then
    pic1="$pic"
    counter=$counter+1
  else
    pic2="$pic"
    pic3="diff"
    pic3="$pic3.$pic1.$pic2.$counter"
    pic3+=".jpeg"
    compare "$pic1" "$pic2" -compose src "$pic3"
    counter=$counter+1
    pic1="$pic2"
  fi
done
